version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=chatbot
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - SECRET_KEY=your-secret-key-here
      - API_KEY=your-api-key-here
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_ENABLED=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    networks:
      - chatbot-network

  celery_worker:
    build: ./backend
    command: celery -A core.celery_app worker --loglevel=info
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=chatbot
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - SECRET_KEY=your-secret-key-here
      - API_KEY=your-api-key-here
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_ENABLED=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis
    volumes:
      - ./backend:/app
    networks:
      - chatbot-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - chatbot-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=chatbot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatbot-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chatbot-network
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  chatbot-network:
    driver: bridge
